In [1]:
#导入NumPy库，生成0到5的数组
import numpy as np
x = np.arange(5)
print (x)

[0 1 2 3 4]


In [2]:
def pySun ():
    a=[1,8,9,13,14]
    b=[9,7,5,15,19]
    C=[7,5,4,23,15]
    d=[]
    for i in range(len(a)):
        d.append(a[i]**2+b[i]**2+C[i]**3)
    return d
%time print(pySun())

[425, 238, 170, 12561, 3932]
CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
def npSun():
    a=np.array([1,8,9,13,14])
    b=np.array([9,7,5,15,19])
    c=np.array([7,5,4,23,15])
    d=a**2+b**2+c**3
    return d
%time print(npSun())

[  425   238   170 12561  3932]
CPU times: total: 0 ns
Wall time: 0 ns


In [5]:
#导入numpy库
import numpy as np
#列表类型创建数组
a=np.array([0,1,2,3])
print(a)
#元组类型创建数组
b=np.array((6,7,8,9))
print(b)

[0 1 2 3]
[6 7 8 9]


In [ ]:
#导入numpy库
#设置起始值10、终止值20,步长2
c= np.arange(10,20,2)
print(c)
#arange创建数组，reshape指定数组尺寸
d=np.arange(12).reshape(3,4)
print(d)

[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
#导入numpy库，取名np
import numpy as np
#默认d0=1,产生[0，1)范围内的一个浮点随机数
a= np.random.rand()
#d0=2，产生[0，1)范围内的一维数组的浮点随机数
b= np.random.rand(2)
#d0=2,d1=3,产生[0,1)范围内的二维数组的浮点随机数
c = np.random.rand(2,3)
print(a)
print(b)
print(c)

0.9215795895009632
[0.40782239 0.99220232]
[[0.99117667 0.61872594 0.32700567]
 [0.35470927 0.91143614 0.12358847]]


In [ ]:
#导入numpy库
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8])
#求最大值、最小值
print(np.max(a))
print(np.min(a))
print(np.average(a))
print(np.var(a))#方差


8
0
4.0
6.666666666666667
